### ISSUE TITLE
yeagerai-agent crashes on start due to broken LangChain import

### ISSUE THREAD

**Issue by jnv** [yeagerai/yeagerai-agent#15]
Hi, I wanted to try yeagerai-agent, but got stuck right on the start. When I install the package and run `yeagerai-agent`, I get the following error:

```
Traceback (most recent call last):
  File " [redacted]/.local/bin/yeagerai-agent", line 5, in <module>
    from yeagerai.interfaces.gradio_chat import main
  File " [redacted]/.local/pipx/venvs/yeagerai-agent/lib64/python3.11/site-packages/yeagerai/interfaces/gradio_chat.py", line 9, in <module>
    from yeagerai.agent import YeagerAIAgent
  File " [redacted]/.local/pipx/venvs/yeagerai-agent/lib64/python3.11/site-packages/yeagerai/agent/__init__.py", line 1, in <module>
    from yeagerai.agent.yeagerai_agent import YeagerAIAgent
  File " [redacted]/.local/pipx/venvs/yeagerai-agent/lib64/python3.11/site-packages/yeagerai/agent/yeagerai_agent.py", line 8, in <module>
    from langchain.callbacks import CallbackManager
ImportError: cannot import name 'CallbackManager' from 'langchain.callbacks' ( [redacted]/.local/pipx/venvs/yeagerai-agent/lib64/python3.11/site-packages/langchain/callbacks/__init__.py)
```

It looks like some version of LangChain moved the CallbackManager to different package: https://github.com/hwchase17/langchain/issues/4332

I see that this [has been addressed](https://github.com/yeagerai/yeagerai-agent/commit/54dac416405e5a3436a9f1a96c2fb67c7b76bed4) by pinning LangChain to older version, but the version 0.0.41 on PyPi doesn't include this change. Do you plan to release the fixed version anytime soon?

Thanks!

**Comment by jnv** [comment]
By the way, I've found two workarounds:

Fix the import in [yeagerai_agent.py](https://github.com/yeagerai/yeagerai-agent/blob/27671911af214ac5f6b402527ee42beab4a330cd/yeagerai/agent/yeagerai_agent.py#L8):

```patch
-from langchain.callbacks import CallbackManager
+from langchain.callbacks.manager import CallbackManager
```

or, when using pipx, inject older LangChain version to the venv:

```shell
pipx inject yeagerai-agent 'langchain==0.0.135'
```

**Comment by jmlago** [comment]
Hi @jnv, thank you very much for your answer and your contribution.

Regarding your question, we are also planning to do a yagents refactor in a couple of weeks, to adapt it to the new [genworlds framework](https://github.com/yeagerai/genworlds).
